Repository edwisdom/chords, pull requests merged in 2020-08, with the labels that each got.

#18 Interval improvements
  src/Base/Core/Accidental.hs
  src/Base/Interval.hs
  src/Lib.hs
  src/Scale.hs
Labels: enhancement, refactor

#17 Chord Substitutions
  chords.cabal
  src/Base/Chord.hs
  src/Base/Chord/Chord.hs
  src/Base/Chord/Extension.hs
  src/Base/Chord/HighestNatural.hs
  src/Base/Chord/Note.hs
  src/Base/Chord/RawChord.hs
  src/Base/Chord/Root.hs
  src/Base/Chord/Sus.hs
  src/Base/Core/Letter.hs
  src/Base/Core/Note.hs
  src/Base/Core/Quality/CQuality.hs
  src/Base/Core/Quality/IQuality.hs
  src/Base/Interval.hs
  src/Base/PitchClass.hs
  src/ChordSubs.hs
  src/Common/Utils.hs
  src/Diatonic.hs
  src/Language/Parser.hs
  src/Lib.hs
  src/Scale.hs
  stack.yaml
Labels: enhancement

#19 WIP: Chord Structure
  app/Main.hs
  chords.cabal
  src/Base/Chord.hs
  src/Base/Chord/Chord.hs
  src/Base/Chord/ChordShape.hs
  src/Base/Chord/ChordSymbol.hs
  src/Base/ChordSymbol.hs
  src/Base/Class/Chordal.hs
  src/Base/Class/Rooted.hs
  src/Base/Heliotonic.hs
  src/ChordSubs.hs
  src/Diatonic.hs
  src/Language/Parser.hs
  src/Lib.hs
Labels: question, refactor

#21 Haddocking
  src/Base/CQuality.hs
  src/Base/Chord/Chord.hs
  src/Base/Chord/ChordShape.hs
  src/Base/Chord/ChordSymbol.hs
  src/Base/Chord/Extension.hs
  src/Base/Chord/HighestNatural.hs
  src/Base/Chord/Note.hs
  src/Base/Chord/RawChord.hs
  src/Base/Chord/Sus.hs
  src/Base/ChordSymbol.hs
  src/Base/Core/Accidental.hs
  src/Base/Core/Letter.hs
  src/Base/Core/Quality/CQuality.hs
  src/Base/Core/Quality/IQuality.hs
  src/Base/Heliotonic.hs
  src/Base/IQuality.hs
  src/Base/Interval.hs
  src/Base/PitchClass.hs
  src/Common/Utils.hs
  src/Language/Parser.hs
Labels: documentation
